{"data": {"repository": {"pullRequest": {"id": "MDExOlB1bGxSZXF1ZXN0NDc1MzA1ODQ2", "number": 4280, "reviewThreads": {"totalCount": 2, "pageInfo": {"startCursor": "Y3Vyc29yOnYyOpK0MjAyMC0wOC0yOFQxMzo0NDoyMFrOEdwDEg==", "endCursor": "Y3Vyc29yOnYyOpK0MjAyMC0wOC0yOFQxMzo0NDoyM1rOEdwDKQ==", "hasNextPage": false, "hasPreviousPage": false}, "nodes": [{"id": "MDIzOlB1bGxSZXF1ZXN0UmV2aWV3VGhyZWFkMjk5NjMxMzc4OnYy", "diffSide": "RIGHT", "path": "ci/Jenkinsfiles/build.groovy", "isResolved": true, "comments": {"totalCount": 4, "pageInfo": {"startCursor": "Y3Vyc29yOnYyOpK0MjAyMC0wOC0yOFQxMzo0NDoyMFrOHJGZwg==", "endCursor": "Y3Vyc29yOnYyOpK0MjAyMC0wOC0yOFQxNTozOTo1OVrOHJLUwQ==", "hasNextPage": false, "hasPreviousPage": false}, "nodes": [{"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQ3OTMwNDEzMA==", "bodyText": "https://www.jenkins.io/doc/pipeline/steps/workflow-basic-steps/#error-error-signal\nsais error aborts the build and avoids printing the stack trace. But since you are printing the error message anyway, why not sticking with the one-liner throw?", "url": "https://github.com/nuxeo/nuxeo/pull/4280#discussion_r479304130", "createdAt": "2020-08-28T13:44:20Z", "author": {"login": "NourNuxeo"}, "path": "ci/Jenkinsfiles/build.groovy", "diffHunk": "@@ -295,7 +295,9 @@ def buildUnitTestStage(env) {\n             }\n           } catch(err) {\n             // TODO NXP-29512: workaround to know which env is failing later on\n-            throw new Exception(\"${env}: ${err.message}\", err)\n+            def errorMessage = \"${env}: ${err.message}\"\n+            echo \"Throwing error with message: ${errorMessage}\"\n+            error \"${errorMessage}\"", "state": "SUBMITTED", "replyTo": null, "originalCommit": {"oid": "112e0df451c21ea64e9a738d4cdec6ad0cc66cd6"}, "originalPosition": 7}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQ3OTMxNTg0OA==", "bodyText": "The reason of the change is all explained in the commit message.\nThe echo here is for debugging purpose, to output the custom message that we're building.\nThe error will then be thrown and catched by the surrounding try/catch block: https://github.com/nuxeo/nuxeo/blob/fix-NXP-29596-fail-PR-build-on-dev-unit-tests-failure/ci/Jenkinsfiles/build.groovy#L540, that might decide to continue or to rethrow, in which case the error message will be finally printed at the end of the build logs.", "url": "https://github.com/nuxeo/nuxeo/pull/4280#discussion_r479315848", "createdAt": "2020-08-28T13:56:53Z", "author": {"login": "ataillefer"}, "path": "ci/Jenkinsfiles/build.groovy", "diffHunk": "@@ -295,7 +295,9 @@ def buildUnitTestStage(env) {\n             }\n           } catch(err) {\n             // TODO NXP-29512: workaround to know which env is failing later on\n-            throw new Exception(\"${env}: ${err.message}\", err)\n+            def errorMessage = \"${env}: ${err.message}\"\n+            echo \"Throwing error with message: ${errorMessage}\"\n+            error \"${errorMessage}\"", "state": "SUBMITTED", "replyTo": {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQ3OTMwNDEzMA=="}, "originalCommit": {"oid": "112e0df451c21ea64e9a738d4cdec6ad0cc66cd6"}, "originalPosition": 7}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQ3OTMzMjQzMA==", "bodyText": "Ok I get it. So this echo will be done as long as we catch and if in dev environment, the message will be printed at the end of the logs to facilitate seeing  it", "url": "https://github.com/nuxeo/nuxeo/pull/4280#discussion_r479332430", "createdAt": "2020-08-28T14:14:24Z", "author": {"login": "NourNuxeo"}, "path": "ci/Jenkinsfiles/build.groovy", "diffHunk": "@@ -295,7 +295,9 @@ def buildUnitTestStage(env) {\n             }\n           } catch(err) {\n             // TODO NXP-29512: workaround to know which env is failing later on\n-            throw new Exception(\"${env}: ${err.message}\", err)\n+            def errorMessage = \"${env}: ${err.message}\"\n+            echo \"Throwing error with message: ${errorMessage}\"\n+            error \"${errorMessage}\"", "state": "SUBMITTED", "replyTo": {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQ3OTMwNDEzMA=="}, "originalCommit": {"oid": "112e0df451c21ea64e9a738d4cdec6ad0cc66cd6"}, "originalPosition": 7}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQ3OTM4NDc2OQ==", "bodyText": "If not on a PR and in dev yes.\nThe error is then simply propagated as for any kind of failure, so the pipeline will naturally make the build fail and display the error message at the end of the logs.", "url": "https://github.com/nuxeo/nuxeo/pull/4280#discussion_r479384769", "createdAt": "2020-08-28T15:39:59Z", "author": {"login": "ataillefer"}, "path": "ci/Jenkinsfiles/build.groovy", "diffHunk": "@@ -295,7 +295,9 @@ def buildUnitTestStage(env) {\n             }\n           } catch(err) {\n             // TODO NXP-29512: workaround to know which env is failing later on\n-            throw new Exception(\"${env}: ${err.message}\", err)\n+            def errorMessage = \"${env}: ${err.message}\"\n+            echo \"Throwing error with message: ${errorMessage}\"\n+            error \"${errorMessage}\"", "state": "SUBMITTED", "replyTo": {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQ3OTMwNDEzMA=="}, "originalCommit": {"oid": "112e0df451c21ea64e9a738d4cdec6ad0cc66cd6"}, "originalPosition": 7}]}}, {"id": "MDIzOlB1bGxSZXF1ZXN0UmV2aWV3VGhyZWFkMjk5NjMxNDAxOnYy", "diffSide": "RIGHT", "path": "ci/Jenkinsfiles/build.groovy", "isResolved": true, "comments": {"totalCount": 2, "pageInfo": {"startCursor": "Y3Vyc29yOnYyOpK0MjAyMC0wOC0yOFQxMzo0NDoyM1rOHJGZ7Q==", "endCursor": "Y3Vyc29yOnYyOpK0MjAyMC0wOC0yOFQxNDowMjo1NlrOHJHejA==", "hasNextPage": false, "hasPreviousPage": false}, "nodes": [{"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQ3OTMwNDE3Mw==", "bodyText": "Suggested change\n        \n          \n    \n\n        \n      \n    \n    \n      \n          \n            \n                            Waiting for NXP-29512, on a PR, the build continues even if there is a unit test error in other\n          \n          \n            \n                            environments than the dev one.\n          \n          \n            \n                            While waiting for NXP-29512 to be resolved, the build in non-dev environment continues even if there are unit test error.", "url": "https://github.com/nuxeo/nuxeo/pull/4280#discussion_r479304173", "createdAt": "2020-08-28T13:44:23Z", "author": {"login": "NourNuxeo"}, "path": "ci/Jenkinsfiles/build.groovy", "diffHunk": "@@ -536,10 +538,17 @@ pipeline {\n           try {\n             parallel stages\n           } catch (err) {\n-            // TODO NXP-29512: on PR, make the build continue even if there is a test error\n+            // TODO NXP-29512: on a PR, make the build continue even if there is a test error\n             // on other environments than the dev one\n             // to remove when all test environments will be mandatory\n-            if (!isPullRequest() || err.message.startsWith(\"dev:\")) {\n+            def errorMessage = err.message\n+            if (isPullRequest() && !errorMessage.startsWith(\"dev:\")) {\n+              echo \"\"\"\n+                Unit tests error: ${errorMessage}\n+                Waiting for NXP-29512, on a PR, the build continues even if there is a unit test error in other\n+                environments than the dev one.", "state": "SUBMITTED", "replyTo": null, "originalCommit": {"oid": "112e0df451c21ea64e9a738d4cdec6ad0cc66cd6"}, "originalPosition": 25}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQ3OTMyMTc0MA==", "bodyText": "on a PR\n\nCannot remove this, it's representative, look at the actual test in the if.\nFor the the beginning of the sentence, not sure about the added value: suggestion is longer, we try to keep things short.\nFor the end, it is not that clear: \"the build in non-dev environment continues\" suggests that only the build that would take place in the dev environment (so the \"dev unit tests stage\"?) would continue. In fact, we're talking about the whole build.", "url": "https://github.com/nuxeo/nuxeo/pull/4280#discussion_r479321740", "createdAt": "2020-08-28T14:02:56Z", "author": {"login": "ataillefer"}, "path": "ci/Jenkinsfiles/build.groovy", "diffHunk": "@@ -536,10 +538,17 @@ pipeline {\n           try {\n             parallel stages\n           } catch (err) {\n-            // TODO NXP-29512: on PR, make the build continue even if there is a test error\n+            // TODO NXP-29512: on a PR, make the build continue even if there is a test error\n             // on other environments than the dev one\n             // to remove when all test environments will be mandatory\n-            if (!isPullRequest() || err.message.startsWith(\"dev:\")) {\n+            def errorMessage = err.message\n+            if (isPullRequest() && !errorMessage.startsWith(\"dev:\")) {\n+              echo \"\"\"\n+                Unit tests error: ${errorMessage}\n+                Waiting for NXP-29512, on a PR, the build continues even if there is a unit test error in other\n+                environments than the dev one.", "state": "SUBMITTED", "replyTo": {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQ3OTMwNDE3Mw=="}, "originalCommit": {"oid": "112e0df451c21ea64e9a738d4cdec6ad0cc66cd6"}, "originalPosition": 25}]}}]}}}, "rateLimit": {"limit": 5000, "remaining": 4364, "cost": 1, "resetAt": "2021-11-03T18:41:40Z"}}}